[package]
name = "client"
version = "0.1.0"
authors = ["KunoiSayami <46131041+KunoiSayami@users.noreply.github.com>"]
edition = "2018"


[dependencies]
reqwest = { version = "0.10", features = ["json", "blocking"] }
configparser = "1.0.0"
base64 = "0.13.0"