[package]
name = "client"
version = "0.1.0"
authors = ["KunoiSayami <46131041+KunoiSayami@users.noreply.github.com>"]
edition = "2018"


[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
configparser = "3.0.2"
base64 = "0.21.0"
